# Generated by Django 4.1 on 2022-09-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_spends',
            name='amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
